const refs = {
  gallery: document.querySelector('.list_film'),
  library: document.querySelector('.page__library'),
  home: document.querySelector('.page__home'),
  headerContainer: document.querySelector('.header'),
  libraryButtonBox: document.querySelector('.library__button-box'),
  navigate: document.querySelector('.navigate__list'),
  searchForm: document.querySelector('.form__search'),
  searchHelper: document.querySelector('.search-helper'),
  btnWatched: document.querySelector('.btn-watched'),
  btnQueue: document.querySelector('.btn-queue'),
  preloader: document.querySelector('.preloader'),
  tuiContainer: document.getElementById('tui-pagination-container'),
  backdrop: document.querySelector('.backdrop'),
  closeBtn: document.querySelector('.close__button'),
  body: document.querySelector('body'),
  movieTitle: document.querySelector('.detail__film__title'),
  detailImg: document.querySelector('.detail__img'),
  vote_average: document.querySelector('.detail__item__info__value__rating'),
  vote_count: document.querySelector('.detail__item__info__value__votes'),
  popularity: document.querySelector('.popularity'),
  originalTitle: document.querySelector('.original__title'),
  overview: document.querySelector('.detail__about__text'),
  genres: document.querySelector('.genres'),
  movieTrailer:document.querySelector('.modal-traill'),
  btnWatchedModal: document.querySelector('.watched'),
  btnQueueModal: document.querySelector('.queue'),
  spanWatched: document.querySelector('.span-watched'),
  spanQueue: document.querySelector('.span-queue'),
  spanWatchedAdd: document.querySelector('.span-watched_add'),
  spanQueueAdd: document.querySelector('.span-queue_add'),
  buttonBlock: document.querySelector('.detail__buttons_block'),
  imageGallery: document.querySelector('.detail__image__gallery'),
  upcomingMovies: document.querySelector('.upcoming__list'),
  modal: document.querySelector(".modal"),
  upcomingTitle: document.querySelector('.upcoming-title'),
  secondModBlockEl: document.querySelector('.second__modal'),
  secondModalBtn: document.querySelector('.second__modal__btn'),
};
export default refs;
